### ISSUE TITLE
fix: if login fails it doesn't notify the user

### ISSUE THREAD

**Issue by mishelashala** [ksquareincmx/conference-client#134]

**Comment by basultobdKs** [comment]
![image](https://user-images.githubusercontent.com/47125452/56339730-04234900-6175-11e9-9768-c7361ba57572.png)

What do you think @mishelashala , maybe for the moment this can be a solution.

**Comment by mishelashala** [comment]
looks good to me

**Comment by basultobdKs** [comment]
Fixed in #140
