### ISSUE TITLE
cannot edit a booking

### ISSUE THREAD

**Issue by mishelashala** [ksquareincmx/conference-client#160]
when i hit edit this is the behavior:

<img width="526" alt="Screen Shot 2019-04-24 at 15 44 07" src="https://user-images.githubusercontent.com/5624153/56692475-e93a6280-66a7-11e9-8a34-6e3eef61e0e8.png">

**Comment by javiermijangosksquare** [comment]
This issue was resolved by resolving a bug in the back end
[back end pull request](https://github.com/ksquareincmx/conference-server/pull/105)
