### ISSUE TITLE
[Bug] Token expired

### ISSUE THREAD

**Issue by holaontiveros** [ksquareincmx/conference-client#222]
At the token expiration and receiving a 401 code from the server the data about the token it's not getting cleared, resulting in an error page and no obvious way of being able to use the app.

![image](https://user-images.githubusercontent.com/4388505/60280982-a1170680-98c9-11e9-90d2-996bacfd5e9d.png)

There should be a system in place that in case of a 401 that it's related to token expiration the local storage get's cleared.

**Comment by martiuh** [comment]
@mishelashala, should we close this issue?
