### ISSUE TITLE
add: index.ts to services

### ISSUE THREAD

**Issue by mishelashala** [ksquareincmx/conference-client#44]
Add an `index.ts` to services

The problem I see rn in `StorageService` is that it exports a `factory function`. Every consumer of `StorageService` needs to execute the function to have access to the instance, we can initialize the instance in the `index.ts` file and export it. So every consumer don't have to do it manually.

```ts
// index.ts
import { StorageService } from './StorageService'
import * as authService from './AuthService'

const storageService = StorageService()

export { storageService, authService }
```

**Comment by basultobdKs** [comment]
All the providers use their own service, except `storageService` that as you see, its used in the `Auth` prov. What do you think if we ininitialize all the services in `index.ts`?

**Comment by mishelashala** [comment]
Yeah, that's the point :) sorry for not expressing it better
