### ISSUE TITLE
add: http api gateway

### ISSUE THREAD

**Issue by mishelashala** [ksquareincmx/conference-client#47]
Implement an `HttpApiGateway` that implements the following interface:

[ApiGateway.pdf](https://github.com/ksquarelabsmx/conference-client/files/2916346/Untitled.Diagram.pdf)

**Comment by basultobdKs** [comment]
@mishelashala Where is going to ble placed in the architecture? Sounds that we are going to have an API service where will be placed all the available operations?

**Comment by basultobdKs** [comment]
Maybe something like this:

```js
const get = async bookingID => {
    const url = `${API_URI}booking/${bookingID}`;
    const res = await fetch(url, {
      method: "GET",
      headers,
    });
    const data = await res.json();
    return data;
};

// Consuming it like this
bookingAPI.get(bookingID);
```

**Comment by mishelashala** [comment]
It's an api gateway so... `src/api-gateways/` looks good to me.

The problem is that `delete` it's a reserved keyword on javascript. `doDelete` avoids the name collision.

We could use a programatic approach, but I prefer start small (as basic as possible) but having a strong separation of concerns.

**Comment by basultobdKs** [comment]
doDelete sounds good for me also. Ok... so inside the folder will be nested folders with the diferente kind of resources that the API has?

**Comment by mishelashala** [comment]
I don't think understand what you mean. Could you provide some context?

**Comment by basultobdKs** [comment]
Yep.

```
src/api-gateways/booking
src/api-gateways/user
```

Each folder has their `api-gateway` file

**Comment by mishelashala** [comment]
The idea of the `api-gateway` is to be... well they gateway between the our application (app domain) and the api (outside world). It needs to be just one file `HttpApiGateway.ts` located at `api-gateways`.

```
+-------------+             +----------------+  communicates   +-----+
| UserService | -- uses --> | HttpApiGateway | ---- with ----> | API |
+-------------+             +----------------+  through http   +-----+
```

**Comment by basultobdKs** [comment]
Completed in #88 .
