### ISSUE TITLE
refactor `components/NavBar`

### ISSUE THREAD

**Issue by mishelashala** [ksquareincmx/conference-client#61]
## AvatarButton
1. Convert function declaration into a expression
2. Use object destructuring on props
```diff
- export function AvatarButton(props) {
+ export const AvatarButon = ({ anchorEl, onClick }) => {
```

## LeftSide
1. Convert function declaration into a expression
2. Use object destructuring on props
3. Delete `Fragment`
4. Used named exports
5. Rename extension to `jsx`
```diff
- function LeftSide (props) {
- // ...
-      <React.Fragment>{props.children}</React.Fragment>
- // ...
- export default LeftSide
+ export const LeftSide = ({ children }) => {
+ // ...
+      {children}
+ // ...
```

## NavBarContainer
1. Convert function declaration into a expression
2. Use object destructuring on props
3. Use named exports
4. Rename extension to `jsx`

## NavBarMenu
1. Convert function declaration into a expression
2. Delete commented code
3. Rename extension to `jsx`

## RightSide
1. Convert function declaration into a expression
2. Use object destructuring on props
3. Use named exports
4. Delete `Fragment`
5. Rename extension to `jsx`

## UserNameLabel
1. Rename to `UserNameLabel`
2. Convert function declaration into a expression
3. Use object destructuring on props

**Comment by basultobdKs** [comment]
Completed in #82
